
Launching defaultServer (WebSphere Application Server 22.0.0.12/wlp-1.0.71.cl221220221107-1900) on Eclipse OpenJ9 VM, version 11.0.18+10 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/server.xml
[5/10/23, 8:54:30:522 UTC] 00000001 FrameworkMana I   CWWKE0002I: The kernel started after 1.78 seconds
[5/10/23, 8:54:30:526 UTC] 00000027 FeatureManage I   CWWKF0007I: Feature update started.
[5/10/23, 8:54:30:634 UTC] 00000027 ConfigValidat A   CWWKG0102I: Found conflicting settings for defaultKeyStore instance of keyStore configuration.
  Property password has conflicting values:
    Secure value is set in file:/opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml.
    Secure value is set in file:/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/server.xml.
  Property password will be set to the value defined in file:/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/server.xml.

[5/10/23, 8:54:30:866 UTC] 0000001e DropinMonitor A   CWWKZ0058I: Monitoring dropins for applications.
[5/10/23, 8:54:31:922 UTC] 0000002a AppMessageHel I   CWWKZ0018I: Starting application cp4waiops-grpc-impact-client.
[5/10/23, 8:54:31:925 UTC] 0000002a WARDeployedAp I   CWWKZ0136I: The cp4waiops-grpc-impact-client application is using the archive file at the /opt/ibm/wlp/usr/servers/defaultServer/apps/cp4waiops-grpc-impact-client.war location.
[5/10/23, 8:54:32:311 UTC] 00000021 WSKeyStore    I   Successfully loaded default keystore: /opt/cert/keystore.p12 of type: PKCS12
[5/10/23, 8:54:32:530 UTC] 00000028 WebGroup      I   SRVE0169I: Loading Web Module: health.
[5/10/23, 8:54:32:609 UTC] 00000028 webcontainer  I com.ibm.ws.webcontainer.osgi.DynamicVirtualHost addWebApplication SRVE0250I: Web Module health has been bound to default_host.
[5/10/23, 8:54:32:610 UTC] 00000028 VirtualHostIm A   CWWKT0016I: Web application available (default_host): http://ibm-grpc-impact-connector-1fd007d1-a141-4e51-a1c9-5e2fd44akkgmr:9080/health/
[5/10/23, 8:54:32:712 UTC] 00000028 WASSessionCor I SessionMgrComponentImpl initialize SESN8501I: The session manager did not find a persistent storage location; HttpSession objects will be stored in the local application server's memory.
[5/10/23, 8:54:32:722 UTC] 00000029 WASSessionCor I SessionContextRegistryImpl getSessionContext SESN0176I: A new session context will be created for application key default_host/health
[5/10/23, 8:54:32:728 UTC] 00000029 util          I IDGeneratorImpl IDGeneratorImpl SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[5/10/23, 8:54:33:054 UTC] 00000029 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [io.openliberty.microprofile.health.3.1.internal] [/health] [HealthCheckReadinessServlet]: Initialization successful.
[5/10/23, 8:54:33:106 UTC] 00000029 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [io.openliberty.microprofile.health.3.1.internal] [/health] [HealthCheckServlet]: Initialization successful.
[5/10/23, 8:54:33:108 UTC] 00000029 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [io.openliberty.microprofile.health.3.1.internal] [/health] [HealthCheckStartupServlet]: Initialization successful.
[5/10/23, 8:54:33:110 UTC] 00000029 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [io.openliberty.microprofile.health.3.1.internal] [/health] [HealthCheckLivenessServlet]: Initialization successful.
[5/10/23, 8:54:33:728 UTC] 00000028 PluginGenerat I   SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /opt/ibm/wlp/output/defaultServer/logs/state/plugin-cfg.xml.
[5/10/23, 8:54:34:313 UTC] 0000002a Version       I org.jboss.weld.bootstrap.WeldStartup <clinit> WELD-000900: 3.1.9 (Final)
[5/10/23, 8:54:36:236 UTC] 0000002a WebGroup      I   SRVE0169I: Loading Web Module: cp4waiops-grpc-impact-client.
[5/10/23, 8:54:36:236 UTC] 0000002a webcontainer  I com.ibm.ws.webcontainer.osgi.DynamicVirtualHost addWebApplication SRVE0250I: Web Module cp4waiops-grpc-impact-client has been bound to default_host.
[5/10/23, 8:54:36:237 UTC] 0000002a VirtualHostIm A   CWWKT0016I: Web application available (default_host): http://ibm-grpc-impact-connector-1fd007d1-a141-4e51-a1c9-5e2fd44akkgmr:9080/
[5/10/23, 8:54:36:239 UTC] 00000035 WASSessionCor I SessionContextRegistryImpl getSessionContext SESN0176I: A new session context will be created for application key default_host/
[5/10/23, 8:54:36:240 UTC] 00000035 util          I IDGeneratorImpl IDGeneratorImpl SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[5/10/23, 8:54:36:316 UTC] 00000029 PluginGenerat I   SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /opt/ibm/wlp/output/defaultServer/logs/state/plugin-cfg.xml.
[5/10/23, 8:54:36:355 UTC] 00000035 ConnectorMana I   Init KafkaHelper
[5/10/23, 8:54:36:355 UTC] 00000035 ConnectorMana W   KAFKA_BOOTSTRAP_SERVERS environment variable does not exist
[5/10/23, 8:54:36:355 UTC] 00000035 ConnectorMana W   KAFKA_SCRAM_PASSWORD_PATH environment variable does not exist
[5/10/23, 8:54:36:356 UTC] 00000035 ConnectorMana W   KAFKA_TRUSTSTORE_PASSWORD_PATH environment variable does not exist
[5/10/23, 8:54:36:356 UTC] 00000035 ConnectorMana W   KAFKA_TRUSTSTORE_PATH environment variable does not exist
[5/10/23, 8:54:36:356 UTC] 00000035 ConnectorMana W   KAFKA_PROD_ACKS environment variable does not exist
[5/10/23, 8:54:36:356 UTC] 00000035 ConnectorMana W   KAFKA_PROD_BATCH_SIZE environment variable does not exist
[5/10/23, 8:54:36:356 UTC] 00000035 ConnectorMana W   KAFKA_PROD_LINGER_MS environment variable does not exist
[5/10/23, 8:54:36:357 UTC] 00000035 ConnectorMana W   KAFKA_PROD_COMPRESSION_TYPE environment variable does not exist
[5/10/23, 8:54:36:357 UTC] 00000035 ConnectorMana W   KAFKA_PROD_BUFFER_MEMORY environment variable does not exist
[5/10/23, 8:54:36:358 UTC] 00000035 ConnectorMana I   isDirectToKafkaSupported: false
[5/10/23, 8:54:36:363 UTC] 00000035 ContextListen I   connector manager initializing
[5/10/23, 8:54:36:610 UTC] 00000035 ConnectorMana I   custom server certificate provided
[5/10/23, 8:54:36:625 UTC] 00000035 ConnectorMana I   client certificate and key provided
[5/10/23, 8:54:36:718 UTC] 00000035 SystemErr     R   SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[5/10/23, 8:54:36:718 UTC] 00000035 SystemErr     R   SLF4J: Defaulting to no-operation (NOP) logger implementation
[5/10/23, 8:54:36:719 UTC] 00000035 SystemErr     R   SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[5/10/23, 8:54:38:166 UTC] 00000035 CloudEventPro I   CloudEventProducer created
[5/10/23, 8:54:38:210 UTC] 00000038 StandardConne I   starting manager
[5/10/23, 8:54:38:210 UTC] 00000039 CloudEventPro I   no produce topics setup, queued events will not be sent until topics have been configured
[5/10/23, 8:54:38:211 UTC] 00000038 StandardConne I   starting configuration stream
[5/10/23, 8:54:38:212 UTC] 00000035 AppMessageHel A   CWWKZ0001I: Application cp4waiops-grpc-impact-client started in 6.290 seconds.
[5/10/23, 8:54:38:231 UTC] 00000027 TCPPort       I   CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host *  (IPv6) port 9080.
[5/10/23, 8:54:38:233 UTC] 00000027 TCPPort       I   CWWKO0219I: TCP Channel defaultHttpEndpoint-ssl has been started and is now listening for requests on host *  (IPv6) port 9443.
[5/10/23, 8:54:38:239 UTC] 00000027 FeatureManage A   CWWKF0012I: The server installed the following features: [cdi-2.0, jndi-1.0, json-1.0, mpConfig-2.0, mpHealth-3.1, servlet-4.0, ssl-1.0].
[5/10/23, 8:54:38:240 UTC] 00000027 FeatureManage I   CWWKF0008I: Feature update completed in 7.722 seconds.
[5/10/23, 8:54:38:240 UTC] 00000027 FeatureManage A   CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 9.499 seconds.
[5/10/23, 8:54:39:146 UTC] 0000003b ConnectorCred I   client id and secret provided
[5/10/23, 8:55:05:456 UTC] 00000027 servlet       I com.ibm.ws.webcontainer.servlet.ServletWrapper init SRVE0242I: [cp4waiops-grpc-impact-client] [/] [com.ibm.aiops.connectors.impact.ConnectorHealthServlet]: Initialization successful.
[5/10/23, 8:55:18:746 UTC] 00000038 Connector     I   Building Impact client
[5/10/23, 8:55:18:857 UTC] 00000038 Connector     I   Impact client created
[5/10/23, 8:55:19:135 UTC] 0000003f ImpactClient  I com.ibm.aiops.connectors.impact.client.ImpactClient sendRequest Sending request: https://nci-0-evtmanager.apps.ocp-270003bu3k-w4q8.cloud.techzone.ibm.com/impactAdmin/restui/policyui/policy/AIOPS_HandleAction/save?xxxnciNoiReqKeyxxx=xxxnciNoiReqValuexxx POST
[5/10/23, 8:55:20:442 UTC] 0000003f ImpactClient  I com.ibm.aiops.connectors.impact.client.ImpactClient sendRequest Sending request: https://nci-0-evtmanager.apps.ocp-270003bu3k-w4q8.cloud.techzone.ibm.com/impactAdmin/restui/policyui/policy/AIOPS_HandleAction/save?xxxnciNoiReqKeyxxx=xxxnciNoiReqValuexxx POST
[5/10/23, 8:55:22:478 UTC] 0000003f ImpactClient  I com.ibm.aiops.connectors.impact.client.ImpactClient sendRequest Sending request: https://nci-0-evtmanager.apps.ocp-270003bu3k-w4q8.cloud.techzone.ibm.com/impactAdmin/restui/policyui/policy/AIOPS_HandleAction/save?xxxnciNoiReqKeyxxx=xxxnciNoiReqValuexxx POST
[5/10/23, 8:55:22:550 UTC] 00000038 StandardConne E   handling connector exception: name=impact-connector,stage=STAGE_CONFIGURE
                                 com.ibm.cp4waiops.connectors.sdk.ConnectorException: Failed to create wrapper policy
	at com.ibm.aiops.connectors.impact.Connector.onConfigure(Connector.java:73)
	at com.ibm.aiops.connectors.actions.ActionConnectorBase.onConfigure(ActionConnectorBase.java:60)
	at com.ibm.cp4waiops.connectors.sdk.StandardConnectorManager.handleConfigurationEvent(StandardConnectorManager.java:332)
	at com.ibm.cp4waiops.connectors.sdk.StandardConnectorManager.processConfigurationUpdates(StandardConnectorManager.java:317)
	at com.ibm.cp4waiops.connectors.sdk.StandardConnectorManager.run(StandardConnectorManager.java:254)
	at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: java.util.concurrent.CompletionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.stopOnError(SSLFlowDelegate.java:934)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:297)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.errorCommon(SubscriberWrapper.java:390)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.onError(SubscriberWrapper.java:381)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:629)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:810)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.handleError(SocketTube.java:747)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher.signalError(SocketTube.java:582)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.signalError(SocketTube.java:425)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.onError(SocketTube.java:393)
	at java.net.http/jdk.internal.net.http.SocketTube.onError(SocketTube.java:138)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:296)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.errorCommon(SubscriberWrapper.java:390)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Writer.processData(SSLFlowDelegate.java:790)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Writer$WriterDownstreamPusher.run(SSLFlowDelegate.java:646)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Writer.schedule(SSLFlowDelegate.java:683)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.resumeActivity(SSLFlowDelegate.java:993)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1092)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:153)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(SSLFlowDelegate.java:1068)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(SSLFlowDelegate.java:1034)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:442)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:264)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$TryEndDeferredCompleter.complete(SequentialScheduler.java:315)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:783)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1073)
	... 13 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 29 more

[5/10/23, 8:55:22:664 UTC] 00000038 ConnectorMana I   writeConnectorStatus() Status: name=Errored retry=0
[5/10/23, 8:55:22:678 UTC] 0000003b ConnectorCred I   client id and secret provided
[5/10/23, 8:55:22:743 UTC] 00000038 ConnectorMana I   writeConnectorStatus() Status: name=Retrying retry=0
[5/10/23, 8:55:22:749 UTC] 0000003b ConnectorCred I   client id and secret provided
[5/10/23, 8:55:27:912 UTC] 0000003f ImpactClient  I com.ibm.aiops.connectors.impact.client.ImpactClient sendRequest Sending request: https://nci-0-evtmanager.apps.ocp-270003bu3k-w4q8.cloud.techzone.ibm.com/impactAdmin/restui/policyui/policy/AIOPS_HandleAction/save?xxxnciNoiReqKeyxxx=xxxnciNoiReqValuexxx POST
[5/10/23, 8:55:28:941 UTC] 0000003f ImpactClient  I com.ibm.aiops.connectors.impact.client.ImpactClient sendRequest Sending request: https://nci-0-evtmanager.apps.ocp-270003bu3k-w4q8.cloud.techzone.ibm.com/impactAdmin/restui/policyui/policy/AIOPS_HandleAction/save?xxxnciNoiReqKeyxxx=xxxnciNoiReqValuexxx POST
[5/10/23, 8:55:30:970 UTC] 0000003f ImpactClient  I com.ibm.aiops.connectors.impact.client.ImpactClient sendRequest Sending request: https://nci-0-evtmanager.apps.ocp-270003bu3k-w4q8.cloud.techzone.ibm.com/impactAdmin/restui/policyui/policy/AIOPS_HandleAction/save?xxxnciNoiReqKeyxxx=xxxnciNoiReqValuexxx POST
[5/10/23, 8:55:30:994 UTC] 00000038 StandardConne E   handling connector exception: name=impact-connector,stage=STAGE_CONFIGURE
                                 com.ibm.cp4waiops.connectors.sdk.ConnectorException: Failed to create wrapper policy
	at com.ibm.aiops.connectors.impact.Connector.onConfigure(Connector.java:73)
	at com.ibm.aiops.connectors.actions.ActionConnectorBase.onConfigure(ActionConnectorBase.java:60)
	at com.ibm.cp4waiops.connectors.sdk.StandardConnectorManager.handleConfigurationEvent(StandardConnectorManager.java:332)
	at com.ibm.cp4waiops.connectors.sdk.StandardConnectorManager.processConfigurationUpdates(StandardConnectorManager.java:317)
	at com.ibm.cp4waiops.connectors.sdk.StandardConnectorManager.run(StandardConnectorManager.java:254)
	at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: java.util.concurrent.CompletionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.stopOnError(SSLFlowDelegate.java:934)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:297)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.errorCommon(SubscriberWrapper.java:390)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.onError(SubscriberWrapper.java:381)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:629)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:810)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.handleError(SocketTube.java:747)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher.signalError(SocketTube.java:582)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.signalError(SocketTube.java:425)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalWriteSubscriber.onError(SocketTube.java:393)
	at java.net.http/jdk.internal.net.http.SocketTube.onError(SocketTube.java:138)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:296)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.errorCommon(SubscriberWrapper.java:390)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Writer.processData(SSLFlowDelegate.java:790)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Writer$WriterDownstreamPusher.run(SSLFlowDelegate.java:646)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Writer.schedule(SSLFlowDelegate.java:683)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.resumeActivity(SSLFlowDelegate.java:993)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1092)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:153)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.executeTasks(SSLFlowDelegate.java:1068)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.doHandshake(SSLFlowDelegate.java:1034)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:442)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:264)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$TryEndDeferredCompleter.complete(SequentialScheduler.java:315)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:783)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate.lambda$executeTasks$3(SSLFlowDelegate.java:1073)
	... 13 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 29 more

[5/10/23, 8:55:31:005 UTC] 00000038 ConnectorMana I   writeConnectorStatus() Status: name=Errored retry=0
[5/10/23, 8:55:31:009 UTC] 0000003b ConnectorCred I   client id and secret provided
[5/10/23, 8:55:31:026 UTC] 00000038 ConnectorMana I   writeConnectorStatus() Status: name=Retrying retry=0
[5/10/23, 8:55:31:029 UTC] 0000003b ConnectorCred I   client id and secret provided
